d /var/lib/cosmic-greeter 0755 cosmic-greeter cosmic-greeter -
d /var/lib/cosmic-greeter/.config 0755 cosmic-greeter cosmic-greeter -
d /var/lib/cosmic-greeter/.config/cosmic 0755 cosmic-greeter cosmic-greeter -
d /var/lib/cosmic-greeter/.config/cosmic/comp 0755 cosmic-greeter cosmic-greeter -
d /var/lib/cosmic-greeter/.local 0755 cosmic-greeter cosmic-greeter -
d /var/lib/cosmic-greeter/.local/state 0755 cosmic-greeter cosmic-greeter -
d /var/lib/cosmic-greeter/.local/state/cosmic-comp 0755 cosmic-greeter cosmic-greeter -
d /var/lib/cosmic-greeter/.local/share 0755 cosmic-greeter cosmic-greeter -
d /var/lib/cosmic-greeter/.local/share/cosmic 0755 cosmic-greeter cosmic-greeter -
d /var/lib/cosmic-greeter/.local/share/cosmic/comp 0755 cosmic-greeter cosmic-greeter -
d /var/lib/cosmic-greeter/.cache 0755 cosmic-greeter cosmic-greeter -
d /var/lib/cosmic-greeter/.cache/cosmic 0755 cosmic-greeter cosmic-greeter -
